# Generated by Django 5.1.2 on 2024-10-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_socialauthsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialAuthSetting',
        ),
        migrations.AlterField(
            model_name='userip',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='userip',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='userip',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='userip',
            name='register_ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Register IP'),
        ),
    ]
